name: Push Event

on: push

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -d '{"after": "${{ github.sha }}", "pusher": {"name": "${{ github.actor }}"}, "ref": "${{ github.ref }}"}' \
          https://webhook-repo-two.vercel.app/webhook/receiver
